class HistoryData {
  static const List<Map<String, String>> statusLogs = [
    {
      'date': '13/09/2025',
      'time': '13:05',
      'status': 'ALL STATUS SYSTEM IS NORMAL',
      'user': 'aldoni',
    },
    {
      'date': '13/09/2025',
      'time': '14:05',
      'status': 'ALL STATUS SYSTEM IS NORMAL',
      'user': 'user2',
    },
    {
      'date': '13/09/2025',
      'time': '15:05',
      'status': 'ALL STATUS SYSTEM IS NORMAL',
      'user': 'aldoni',
    },
    {
      'date': '13/09/2025',
      'time': '16:05',
      'status': 'ALL STATUS SYSTEM IS NORMAL',
      'user': 'admin',
    },
    {
      'date': '13/09/2025',
      'time': '17:05',
      'status': 'ALL STATUS SYSTEM IS NORMAL',
      'user': 'aldoni',
    },
    {
      'date': '13/09/2025',
      'time': '18:05',
      'status': 'ALL STATUS SYSTEM IS NORMAL',
      'user': 'user2',
    },
    {
      'date': '13/09/2025',
      'time': '19:05',
      'status': 'ALL STATUS SYSTEM IS NORMAL',
      'user': 'aldoni',
    },
    {
      'date': '13/09/2025',
      'time': '20:05',
      'status': 'ALL STATUS SYSTEM IS NORMAL',
      'user': 'admin',
    },
    {
      'date': '13/09/2025',
      'time': '21:05',
      'status': 'SYSTEM RESET',
      'user': 'aldoni',
    },
    {
      'date': '13/09/2025',
      'time': '22:05',
      'status': 'ALL STATUS SYSTEM IS NORMAL',
      'user': 'user2',
    },
    {
      'date': '13/09/2025',
      'time': '23:05',
      'status': 'ALL STATUS SYSTEM IS NORMAL',
      'user': 'aldoni',
    },
    {
      'date': '14/09/2025',
      'time': '00:05',
      'status': 'ALL STATUS SYSTEM IS NORMAL',
      'user': 'admin',
    },
    {
      'date': '14/09/2025',
      'time': '01:05',
      'status': 'ALL STATUS SYSTEM IS NORMAL',
      'user': 'aldoni',
    },
    {
      'date': '14/09/2025',
      'time': '02:05',
      'status': 'ALL STATUS SYSTEM IS NORMAL',
      'user': 'user2',
    },
    {
      'date': '14/09/2025',
      'time': '03:05',
      'status': 'ALL STATUS SYSTEM IS NORMAL',
      'user': 'aldoni',
    },
  ];

  static const List<Map<String, String>> connectionLogs = [
    {
      'date': '13/09/2025',
      'time': '13:05',
      'information': 'Module #01 Connected',
    },
    {
      'date': '13/09/2025',
      'time': '14:05',
      'information': 'Module #02 Connected',
    },
    {
      'date': '13/09/2025',
      'time': '15:05',
      'information': 'Module #03 Connected',
    },
    {
      'date': '13/09/2025',
      'time': '16:05',
      'information': 'Module #04 Connected',
    },
    {
      'date': '13/09/2025',
      'time': '17:05',
      'information': 'Module #05 Connected',
    },
    {
      'date': '13/09/2025',
      'time': '18:05',
      'information': 'All Modules Connected',
    },
    {'date': '13/09/2025', 'time': '19:05', 'information': 'System Online'},
    {
      'date': '13/09/2025',
      'time': '20:05',
      'information': 'Backup Power Active',
    },
    {'date': '13/09/2025', 'time': '21:05', 'information': 'Network Stable'},
    {'date': '13/09/2025', 'time': '22:05', 'information': 'All Zones Active'},
    {
      'date': '13/09/2025',
      'time': '23:05',
      'information': 'System Check Passed',
    },
    {
      'date': '14/09/2025',
      'time': '00:05',
      'information': 'Daily Backup Completed',
    },
    {
      'date': '14/09/2025',
      'time': '01:05',
      'information': 'Maintenance Mode Off',
    },
    {
      'date': '14/09/2025',
      'time': '02:05',
      'information': 'All Systems Normal',
    },
    {'date': '14/09/2025', 'time': '03:05', 'information': 'Connection Stable'},
  ];

  static const List<Map<String, String>> troubleLogs = [
    {
      'date': '13/09/2025',
      'time': '13:05',
      'address': '#01-1',
      'zoneName': 'RUANG TUNGGU',
      'status': 'OPEN CIRCUIT',
    },
    {
      'date': '13/09/2025',
      'time': '14:05',
      'address': '#01-2',
      'zoneName': 'RUANG MAKAN',
      'status': 'SHORT CIRCUIT',
    },
    {
      'date': '13/09/2025',
      'time': '15:05',
      'address': '#02-1',
      'zoneName': 'LOBBY',
      'status': 'GROUND FAULT',
    },
    {
      'date': '13/09/2025',
      'time': '16:05',
      'address': '#02-2',
      'zoneName': 'KORIDOR',
      'status': 'OPEN CIRCUIT',
    },
    {
      'date': '13/09/2025',
      'time': '17:05',
      'address': '#03-1',
      'zoneName': 'APOTEK',
      'status': 'SHORT CIRCUIT',
    },
    {
      'date': '13/09/2025',
      'time': '18:05',
      'address': '#03-2',
      'zoneName': 'RUANG OPERASI',
      'status': 'GROUND FAULT',
    },
    {
      'date': '13/09/2025',
      'time': '19:05',
      'address': '#04-1',
      'zoneName': 'ICU',
      'status': 'OPEN CIRCUIT',
    },
    {
      'date': '13/09/2025',
      'time': '20:05',
      'address': '#04-2',
      'zoneName': 'RUANG RAWAT',
      'status': 'SHORT CIRCUIT',
    },
    {
      'date': '13/09/2025',
      'time': '21:05',
      'address': '#05-1',
      'zoneName': 'PARKIR',
      'status': 'GROUND FAULT',
    },
    {
      'date': '13/09/2025',
      'time': '22:05',
      'address': '#05-2',
      'zoneName': 'GUDANG',
      'status': 'OPEN CIRCUIT',
    },
    {
      'date': '13/09/2025',
      'time': '23:05',
      'address': '#01-3',
      'zoneName': 'TOILET',
      'status': 'SHORT CIRCUIT',
    },
    {
      'date': '14/09/2025',
      'time': '00:05',
      'address': '#02-3',
      'zoneName': 'DAPUR',
      'status': 'GROUND FAULT',
    },
    {
      'date': '14/09/2025',
      'time': '01:05',
      'address': '#03-3',
      'zoneName': 'LABORATORIUM',
      'status': 'OPEN CIRCUIT',
    },
    {
      'date': '14/09/2025',
      'time': '02:05',
      'address': '#04-3',
      'zoneName': 'ADMIN',
      'status': 'SHORT CIRCUIT',
    },
    {
      'date': '14/09/2025',
      'time': '03:05',
      'address': '#05-3',
      'zoneName': 'KEAMANAN',
      'status': 'GROUND FAULT',
    },
  ];

  static const List<Map<String, String>> fireLogs = [
    {
      'date': '13/09/2025',
      'time': '13:05',
      'address': '#01-1',
      'zoneName': 'RUANG TUNGGU',
      'status': 'FIRE ALARM',
    },
    {
      'date': '13/09/2025',
      'time': '14:05',
      'address': '#01-2',
      'zoneName': 'RUANG MAKAN',
      'status': 'FIRE ALARM',
    },
    {
      'date': '13/09/2025',
      'time': '15:05',
      'address': '#02-1',
      'zoneName': 'LOBBY',
      'status': 'FIRE ALARM',
    },
    {
      'date': '13/09/2025',
      'time': '16:05',
      'address': '#02-2',
      'zoneName': 'KORIDOR',
      'status': 'FIRE ALARM',
    },
    {
      'date': '13/09/2025',
      'time': '17:05',
      'address': '#03-1',
      'zoneName': 'APOTEK',
      'status': 'FIRE ALARM',
    },
    {
      'date': '13/09/2025',
      'time': '18:05',
      'address': '#03-2',
      'zoneName': 'RUANG OPERASI',
      'status': 'FIRE ALARM',
    },
    {
      'date': '13/09/2025',
      'time': '19:05',
      'address': '#04-1',
      'zoneName': 'ICU',
      'status': 'FIRE ALARM',
    },
    {
      'date': '13/09/2025',
      'time': '20:05',
      'address': '#04-2',
      'zoneName': 'RUANG RAWAT',
      'status': 'FIRE ALARM',
    },
    {
      'date': '13/09/2025',
      'time': '21:05',
      'address': '#05-1',
      'zoneName': 'PARKIR',
      'status': 'FIRE ALARM',
    },
    {
      'date': '13/09/2025',
      'time': '22:05',
      'address': '#05-2',
      'zoneName': 'GUDANG',
      'status': 'FIRE ALARM',
    },
    {
      'date': '13/09/2025',
      'time': '23:05',
      'address': '#01-3',
      'zoneName': 'TOILET',
      'status': 'FIRE ALARM',
    },
    {
      'date': '14/09/2025',
      'time': '00:05',
      'address': '#02-3',
      'zoneName': 'DAPUR',
      'status': 'FIRE ALARM',
    },
    {
      'date': '14/09/2025',
      'time': '01:05',
      'address': '#03-3',
      'zoneName': 'LABORATORIUM',
      'status': 'FIRE ALARM',
    },
    {
      'date': '14/09/2025',
      'time': '02:05',
      'address': '#04-3',
      'zoneName': 'ADMIN',
      'status': 'FIRE ALARM',
    },
    {
      'date': '14/09/2025',
      'time': '03:05',
      'address': '#05-3',
      'zoneName': 'KEAMANAN',
      'status': 'FIRE ALARM',
    },
  ];
}
